# Generated by Django 4.2.13 on 2024-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                (
                    "detailing_type",
                    models.CharField(
                        choices=[
                            ("current", "current"),
                            ("minutely", "minutely"),
                            ("hourly", "hourly"),
                            ("daily", "daily"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
